name: Deploy Chocolatey

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Git Tag'
        required: true

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  chocolatey:
    name: Deploy to chocolatey.org
    runs-on: windows-latest
    if: github.repository == 'openhv/openhv'
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Set Checksum
        run: |
          filename="OpenHV-${{ github.event.inputs.tag }}-x86.exe"
          url="https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.tag }}/${filename}"
          sed -i "s#{URL32}#${url}#g" "packaging/windows/chocolatey/tools/chocolateyinstall.ps1"
          curl -sSL "${url}" -o "packaging/windows/${filename}"
          md5=$(cat "packaging/windows/${filename}" | md5sum -)
          sed -i "s/{MD5CHECKSUM32}/${md5:0:32}/g" "packaging/windows/chocolatey/tools/chocolateyinstall.ps1"
          filename="OpenHV-${{ github.event.inputs.tag }}-x64.exe"
          url="https://github.com/${{ github.repository }}/releases/download/${{ github.event.inputs.tag }}/${filename}"
          sed -i "s#{URL64}#${url}#g" "packaging/windows/chocolatey/tools/chocolateyinstall.ps1"
          curl -sSL "${url}" -o "packaging/windows/${filename}"
          md5=$(cat "packaging/windows/${filename}" | md5sum -)
          sed -i "s/{MD5CHECKSUM64}/${md5:0:32}/g" "packaging/windows/chocolatey/tools/chocolateyinstall.ps1"

      - name: Set Version
        id: version
        run: |
          tag=${{ github.event.inputs.tag }}
          version="${tag:0:4}.${tag:4:2}.${tag:6:2}"
          echo "::set-output name=nuget::$version"
          sed -i "s/{VERSION}/${version}/g" "packaging/windows/chocolatey/openhv.nuspec"

      - name: Pack Release
        run: |
          choco pack packaging/windows/chocolatey/openhv.nuspec --outputdirectory packaging/windows/chocolatey

      - name: Upload Release
        run: |
          package=$(find packaging/windows/chocolatey/ -type f -name "*.nupkg")
          choco push $package -s https://push.chocolatey.org/ -k ${{ secrets.CHOCO_KEY }} --allow-unofficial
